language: php
php:
  - "5.5"
  - "7.0"
  - "7.1"
  - "7.2"
before_script:
  - composer selfupdate

install:
    - composer self-update
    - composer install

cache:
    directories:
        - $HOME/.composer/cache

script:
    - vendor/bin/codecept run unit
    - vendor/bin/phpcs src

notifications:
  email:
    on_success: never
    on_failure: change