language: php

php:
  - 7.0
  - 7.1
  - 7.2

import:
  - source: flash-global/travis-public:common.yml@master
    mode: deep_merge_append
  - source: flash-global/travis-public:php/common.yml@master
    mode: deep_merge_append